apiVersion: apps/v1
kind: Deployment

metadata:
  name: my-deploy

spec:
  selector:
    matchLabels:
      app: my-web
  replicas: 3
  template: 
    metadata:
      name: dep1
      labels:
        app: my-web
    spec:
      containers:
        - image: fatmaahmed611/nginx-web
          name: project-container
          resources:
            limits:
              memory: "512Mi"
              cpu: "1"

